name: Typescript CI
'on':
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
jobs:
  typescript-ci:
    uses: IronCoreLabs/workflows/.github/workflows/typescript-ci.yaml@test-typescript-ci-change
    secrets: inherit
